### ISSUE TITLE
Feature : .Net CLR Inititlaiztion

### ISSUE THREAD

**Issue by NobodyWithNoName** [bb107/MemoryModulePP#3]
This library is the best pe loader I've found thanks for your contribution, I was just thinking it would be great if you add .net support, I have not so much information but I know before loading .net dlls with export clr.dll gets initialized, It should be possible to add it to the MMPP, It will be great if you can implement it.

Thanks

**Comment by bb107** [comment]
I don't think I understand why you use MMPP to load .NET assemblies from memory. On the one hand, C++/CLI supports loading assemblies from memory (as shown in Figure 1); on the other hand, if you don’t use C++/CLI, I don’t understand how to call managed code from native code. 
I have adjusted the loader so that it can load .NET assemblies (as shown in Figure 2), but it can only be loaded in 32-bit programs, because as far as I know, almost all .NET assemblies have 32-bit PE headers . But Win32 API LoadLibrary can load the .NET assembly correctly even if it is a 64-bit program.
![A](https://user-images.githubusercontent.com/20726245/144794478-fffc48bc-8881-4952-bc30-c38dd67ff1ce.png)
![B](https://user-images.githubusercontent.com/20726245/144794482-ab32281f-4427-40a1-8a63-6e6eb4355f18.png)

**Comment by NobodyWithNoName** [comment]
Hello, No, there are 64bit assemblies.
You need to set the project **completely to x64**, then use [DllExport ](https://www.nuget.org/packages/DllExport/)package to export functions from managed dll.

Here's a sample x64 managed dll which works fine with LoadLibraryW 
It has one exported function : 
```CPP
typedef void(*ManagedExportFuncType)(const char* str);
```
It shows the text parameter in a message box.
[ManagedLib_x64.zip](https://github.com/bb107/MemoryModulePP/files/7663949/ManagedLib_x64.zip)

**Comment by bb107** [comment]
Hello, thank you for your explanation. When the export function is called for the first time, the initialization function of mscoreei.dll will be called first, and the assembly file version will be checked in it and the cli environment will be loaded. Therefore, to execute the export method in .net correctly, the assembly file must be stored on the hard disk, and its location must be specified when calling LdrLoadDllMemoryExW.
![Snipaste_2021-12-07_09-18-27](https://user-images.githubusercontent.com/20726245/144949991-4580eefb-05a7-4f2a-af65-5599534bdbc0.png)
![Snipaste_2021-12-07_09-21-43](https://user-images.githubusercontent.com/20726245/144949996-509aa650-ff41-4483-bf95-956c9524a15c.png)

**Comment by NobodyWithNoName** [comment]
Nice!, since we are already using detours, can't it be virtualized by hooking some functions?

**Comment by bb107** [comment]
Thank you for your reply. During mscoreei.dll initialization, clr.dll will be loaded and CorDllMainForThunk will be called. This function will remap the assembly we want to execute. Therefore, it is not feasible for us to deal with it by hooking.
![a](https://user-images.githubusercontent.com/20726245/145150498-679d3e47-9188-43c9-b651-a3c08032d531.png)
![b](https://user-images.githubusercontent.com/20726245/145150503-862aab21-9e20-4ace-926b-eeeac6994145.png)
![c](https://user-images.githubusercontent.com/20726245/145150507-10a95eff-b960-41fd-80f7-85f057c0e9b5.png)

**Comment by bb107** [comment]
Anyway, I found the necessary functions through disassembly and dynamic debugging and hooked them:
```
CreateFileW
GetFileInformationByHandle
GetFileAttributesExW
CreateFileMappingW
MapViewOfFileEx
UnmapViewOfFile
CloseHandle
GetFileVersion
```
Then a simple .NET assembly was successfully loaded and called. Due to the complexity of .NET, our hooks cannot guarantee the correct execution of complex assemblies and cross-version compatibility of the .NET framework.

![Snipaste_2021-12-15_10-10-42](https://user-images.githubusercontent.com/20726245/146110306-49bf2e60-dd8c-4a1d-a267-3a18d9b37146.png)

**Comment by NobodyWithNoName** [comment]
**Good job!**

I cloned HandleTlsData and tried a very basic .net dll (the one I sent above) and it didn't work throw a error :
> Microsoft C++ exception: HRException at memory location 0x000000852EEFF838.

Is there any extra step I should do?

**Comment by bb107** [comment]
Hi. You need to specify the ```LOAD_FLAGS_HOOK_DOT_NET``` flag when calling ```LdrLoadDllMemoryExW```. When I was debugging this issue, I found that MmpTls made false assertions when processing some threads created by the kernel that the user could not perceive.

![Snipaste_2021-12-15_22-37-57](https://user-images.githubusercontent.com/20726245/146207538-941e67c7-2b3f-4952-9ce7-2bebbc77cab0.png)

**Comment by NobodyWithNoName** [comment]
If you don't mind, can you upload a sample solution?

**Comment by bb107** [comment]
This bug has been fixed in the [41c1175](https://github.com/bb107/MemoryModulePP/commit/41c1175add82e12600d0dea4b54673488e472e2a) commit.

**Comment by NobodyWithNoName** [comment]
I still can't make it working on a simple hello world dll, It throw HResult error.
Can you push a example for .net to the branch?
Thanks!

**Comment by bb107** [comment]
What is your version of Windows? I tested it on a Windows 7 virtual machine and it also threw an exception, but it worked correctly on another Windows 10 version. Because different versions of clr.dll have different implementations of remapping, it is difficult for us to be compatible with all versions by being compatible with one version.

**Comment by NobodyWithNoName** [comment]
Hi there, I have Win 10 21H1 (1904)

**Comment by bb107** [comment]
Hello, I just updated the code. I think it can work correctly for you. If it still throws an exception, please tell me your .net framework version and clr.dll file version.

**Comment by NobodyWithNoName** [comment]
Hello @bb107 and thanks! The sample you uploaded works with the dll nice! But when I use the same in my LdrLoadDll dll gets loaded but just after that it throws `Unhandled Exception: OutOfMemoryException.` any idea?

**Comment by bb107** [comment]
Hi. I cannot reproduce this exception. Please upload a sample that can trigger this exception.

**Comment by CycloneRing** [comment]
Sure, I'll upload a sample repo in the first chance i've got.
Thanks for your time and work!
